apps/kana/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'apps.kana.views',

    url(r'^$', 'home', name='home'),
    url(r'^chart/(?P<kana>hiragana|katakana)', 'chart', name='chart'),
    url(r'^quiz/(?P<kana>hiragana|katakana)$', 'quiz', name='quiz'),
    url(r'^quiz/(?P<kana>hiragana|katakana)/(?P<group>dakuten|youon|all)', 'quiz', name='quiz'),
)

kana_quiz/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns(
    '',

    # admin
    url(r'^admin/', include(admin.site.urls)),

    # kana app
    url(r'^', include('apps.kana.urls', namespace='kana')),
)

apps/kana/models.py
from django.db import models


class Character(models.Model):

    # characters
    romaji = models.CharField(max_length=3)
    hiragana = models.CharField(max_length=2, unique=True)
    katakana = models.CharField(max_length=2, unique=True)
    # grouping indicators
    is_plain = models.BooleanField()
    is_dakuten = models.BooleanField()
    is_handakuten = models.BooleanField()
    is_youon = models.BooleanField()
    # charting
    gojuon_row = models.IntegerField()
    gojuon_col = models.IntegerField()
    # extra
    alternate_romaji = models.CharField(max_length=3, null=True, blank=True, default=None)
    notes = models.TextField(null=True, blank=True, default=None)

    def save(self, *args, **kwargs):
        if self.is_handakuten:
            self.is_dakuten = True
        super(Character, self).save(*args, **kwargs)

    def __str__(self):
        return self.romaji

apps/kana/views.py
from django.db.models import Q
from django.shortcuts import render_to_response
from django.template import RequestContext

from .models import *


def home(request):
    return render_to_response(
        'kana/home.html', {}, context_instance=RequestContext(request)
    )


def chart(request, kana):
    plain = Character.objects.filter(is_plain=True, is_dakuten=False, is_youon=False)
    dakuten = Character.objects.filter(is_dakuten=True, is_youon=False)
    youon = Character.objects.filter(is_youon=True)

    return render_to_response(
        'kana/chart.html',
        {
            'plain': plain,
            'dakuten': dakuten,
            'youon': youon,
            'kana': kana,
        },
        context_instance=RequestContext(request)
    )


def quiz(request, kana, group=None):
    chars = Character.objects.all()

    if group is None:
        chars = chars.filter(is_plain=True)
    elif group == 'dakuten':
        chars = chars.filter(Q(is_dakuten=True) & Q(is_youon=False))
    elif group == 'youon':
        chars = chars.filter(is_youon=True)
    elif group == 'all':
        pass

    return render_to_response(
        'kana/quiz.html',
        {
            'chars': chars,
            'kana': kana,
        },
        context_instance=RequestContext(request)
    )

apps/kana/templates/kana/chart.html
{% extends 'base/rows.html' %}

{% block content %}
{% load gojuon %}

<div class="row">
  <h1>Kana</h1>
  <p>
    Kana (仮名) are Japanese syllabic scripts.
  </p>
  <p>
    Each character of the kana corresponds to a sound following either a consonant-vowel pattern or a single vowel
    pattern. There is one exception to this: the sound most similar to a Western <em>N</em> sound.
  </p>
  <p>
    Traditional Japanese text is presented in <em>gojuon</em> order: top-down, right to left. This will be the method
    used for the following charts.
  </p>
  <p>
    There are also several blank tiles in the charts. For these blanks, there are no provided written or spoken
    sounds - either they do not exist, or they have been excluded due to modern usage. There are also a few sounds
    that are vocalized slightly differently than the normal pattern would suggest; take note of these special cases.
  </p>
</div>
<br class="clear" />
<br class="clear" />

<div class="row">
  <h2>{{ kana|title }}</h2>
  {% render_as_chart plain kana %}
</div>
<br class="clear" />
<br class="clear" />

<div class="row">
  <h2>Dakuten and Handakuten</h2>
  <p>
    Dakuten (濁点) characters are variants of standard kana characters used to indicated that the consonant of the
    character should be voiced in its alternative form.
  </p>
  <p>
    Handakuten (半濁点) are very similar to Dakuten, with the exception that they are applied only to the <em>H</em>
    consonant stemmed characters to form a <em>P</em> sound.
  </p>
  {% render_as_chart dakuten kana %}
</div>
<br class="clear" />
<br class="clear" />

<div class="row">
  <h2>Youon</h2>
  <p>
    Youon (拗音), or yōon, characters are special patterns in which an <em>I</em> tailed character is combined with a
    <em>Y</em> consonant stemmed character.
  </p>
  {% if kana == 'hiragana' %}
  <p>
    In hiragana, as opposed to katakana, the Y-characters are written with a slightly smaller script. While this change
    is subtle, in cases where only context would lend to the distinction between homonyms, the written form indicates
    the intended word.
  </p>
  {% endif %}
  {% render_as_chart youon kana %}
</div>
<br class="clear" />
<br class="clear" />
{% endblock %}

apps/kana/templates/kana/home.html
{% extends 'base/jumbotron.html' %}

{% block jumbotron %}
<div id="hello" class="hello"></div>
<div>
  <p>
    Welcome to Kana Quiz!
  </p>
</div>
{% endblock %}

{% block contentjs %}
<script type="text/javascript">
  var date = new Date();
  var hour = date.toString().split(" ")[4].split(":")[0];
  var div = $("#hello");
  if (hour >= 4 && hour < 11) { div.text("おはよう!"); }
  else if (hour >= 11 && hour < 19) { div.text("こんにちわ!"); }
  else { div.text("こんばんわ!"); }
</script>
{% endblock %}

apps/kana/templates/kana/quiz.html
{% extends 'base/jumbotron.html' %}

{% load quiz %}


{% block jumbotron %}
  <div id="current-char" class="quiz-char"></div>

  <br /><br /><br />
  <div class="quiz-char" id="form-wrapper">
  <form>
    <div class="col-lg-5">&nbsp;</div><div class="form-group col-lg-2">
      <input type="text" name="user-input" id="user-input" class="form-control" placeholder="romaji" autofocus />
      <button class="btn btn-primary" onclick="check_answer(); return false;">Submit</button>
    </div><div class="col-lg-5">&nbsp;</div>
    <input type="hidden" id="correct-answer" name="correct-answer" />
    <input type="hidden" id="alternate-answer" name="alternate-answer" />
  </form>
  </div>
{% endblock %}


{% block content %}
  <div id="answer-tracker" class="row"></div>
{% endblock %}


{% block contentjs %}
{# run queryset through template tag to generate js array #}
{% make_quiz_js chars kana %}
{# quiz logic #}
{% load static %}
<script src="{% static 'kana/js/quiz_logic.js' %}" type="text/javascript"></script>
{% endblock %}

kana_quiz/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title></title>

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- app link -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'kana:home' %}">Kana Quiz</a>
    </div>
    <!-- /app link -->
    <!-- right float : collapse -->
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'kana:home' %}">Home</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kana Charts<b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'kana:chart' 'hiragana' %}">Hiragana</a></li>
            <li><a href="{% url 'kana:chart' 'katakana' %}">Katakana</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quizzes<b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu">
            <li class="dropdown-header">Hiragana</li>
            <li><a href="{% url 'kana:quiz' 'hiragana' %}">Standard</a></li>
            <li><a href="{% url 'kana:quiz' 'hiragana' 'dakuten' %}">Dakuten &amp; Handakuten</a></li>
            <li><a href="{% url 'kana:quiz' 'hiragana' 'youon' %}">Youon</a></li>
            <li><a href="{% url 'kana:quiz' 'hiragana' 'all' %}">All</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Katakana</li>
            <li><a href="{% url 'kana:quiz' 'katakana' %}">Standard</a></li>
            <li><a href="{% url 'kana:quiz' 'katakana' 'dakuten' %}">Dakuten &amp; Handakuten</a></li>
            <li><a href="{% url 'kana:quiz' 'katakana' 'youon' %}">Youon</a></li>
            <li><a href="{% url 'kana:quiz' 'katakana' 'all' %}">All</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

{% block main_content %}{% endblock %}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

{% block contentjs %}{% endblock %}

</body>
</html>

kana_quiz/templates/base/jumbotron.html
{% extends 'base/base.html' %}

{% block main_content %}
<div class="jumbotron" id="jumbotron">
  <div class="container">
    {% block jumbotron %}{% endblock %}
  </div>
</div>

<div class="container" id="content-main">
  {% block content %}{% endblock %}
</div>
{% endblock %}

kana_quiz/templates/base/rows.html
{% extends 'base/base.html' %}

{% block main_content %}
<div class="container" id="content-main">
  {% block content %}{% endblock %}
</div>
{% endblock %}